#!/bin/bash
TSV_FOLDER="tsv"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy public.user FROM '$TSV_FOLDER/users.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy ubiquity_serviceconsent FROM '$TSV_FOLDER/ubiquity_serviceconsent.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy scheme_scheme FROM '$TSV_FOLDER/scheme_scheme.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy scheme_schemecredentialquestion FROM '$TSV_FOLDER/scheme_schemecredentialquestion.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy scheme_schemeaccount FROM '$TSV_FOLDER/scheme_schemeaccount.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy scheme_schemeaccountcredentialanswer FROM '$TSV_FOLDER/scheme_schemeaccountcredentialanswer.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy payment_card_paymentcardaccount FROM '$TSV_FOLDER/payment_card_paymentcardaccount.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy ubiquity_paymentcardaccountentry FROM '$TSV_FOLDER/ubiquity_paymentcardaccountentry.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy ubiquity_schemeaccountentry FROM '$TSV_FOLDER/ubiquity_schemeaccountentry.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5433 --user postgres -d hermes -c "\copy ubiquity_paymentcardschemeentry FROM '$TSV_FOLDER/ubiquity_paymentcardschemeentry.tsv' DELIMITER E'\t'"
