complexity:
  stage: test
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

style:
  stage: test
  before_script:
    - pip install black
  script:
    - flake8 && black --line-length 120 --check .
