#!/bin/bash
TSV_FOLDER="tsv"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy user_organisation FROM '$TSV_FOLDER/user_organisation.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy user_clientapplication FROM '$TSV_FOLDER/user_clientapplication.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy user_clientapplicationbundle FROM '$TSV_FOLDER/user_clientapplicationbundle.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy scheme_scheme FROM '$TSV_FOLDER/scheme_scheme.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy scheme_schemecredentialquestion FROM '$TSV_FOLDER/scheme_schemecredentialquestion.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy scheme_schemebundleassociation FROM '$TSV_FOLDER/scheme_schemebundleassociation.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hermes -c "\copy scheme_category FROM '$TSV_FOLDER/scheme_category.tsv' DELIMITER E'\t'"
psql -h 127.0.0.1 -p 5432 --user "postgres" -d hades -c "\copy transactions FROM '$TSV_FOLDER/transactions.tsv' DELIMITER E'\t'"
